export { default as Accueil } from "./Accueil";
export { default as Header } from "./Header";
export { default as About } from "./About";
export { default as Places } from "./Places";
export { default as SessionsTasks } from "./SessionsTasks";
export { default as Footer } from './Footer';
export { default as Assignments } from './Assignments';
export { default as UserAssignments } from './UserAssignments';
export { default as Friends } from './Friends';