name: CI [master]
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  build:
    name: Intégration serveur PROD
    runs-on: ubuntu-latest
    steps:
    - name: Update de l'API
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo docker exec api pm2 stop /home/RixRefugees/node/bin/www
          sudo cd /home/gauth/RixRefugees/docker
          sudo docker-compose down
          sudo docker build ./Node -t gonogoat/rixrefugees:api
          sudo docker push gonogoat/rixrefugees:api
          sudo docker-compose up -d
          sudo docker exec api sh -c "cd /home/RixRefugees && git pull"
          sudo docker exec api npm install /home/RixRefugees/node
          sudo docker exec api npm install /home/RixRefugees/react-rixrefugees
          sudo docker exec api sh -c "cd /home/RixRefugees/react-rixrefugees && npm run build"
          sudo docker exec api pm2 start /home/RixRefugees/node/bin/www
