name: CI [master]
on:
  push:
    branches:
      - master
      - docker
  pull_request:
    branches:
      - master
      - docker
jobs:

  build:
    name: Intégration serveur PROD
    runs-on: ubuntu-latest
    steps:
    - name: Update de l'API
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo docker exec api sh -c "cd /home/RixRefugees/node && pm2 stop npm"
          cd /home/gauth/RixRefugees/docker && sudo docker-compose down
          cd /home/gauth/RixRefugees/docker && sudo git pull
          cd /home/gauth/RixRefugees/docker && sudo docker-compose up -d
          sudo docker exec api sh -c "cd /home/RixRefugees && git pull"
          sudo docker exec api sh -c "cd /home/RixRefugees/node && npm install"
          sudo docker exec api sh -c "cd /home/RixRefugees/react-rixrefugees && npm install"
          sudo docker exec api sh -c "cd /home/RixRefugees/react-rixrefugees && npm run build"
          sudo docker exec api sh -c "cd /home/RixRefugees/node && pm2 start npm -- start"
          
